"use client";
import {useEffect,useState,useCallback,useRef,type FormEvent} from 'react';
type Plan={daily_minutes?:number;exam_date?:string;free_day?:string;warning?:string;message?:string;schedule?:{date:string;sessions:{topic:string;minutes:number;activity:string}[]}[]};
type Profile={profile:{scores:Record<string,number>;exam_date?:string};history:{role:string;message:string}[];plan:Plan|null;syllabus_topics:string[]};
export default function LearningPanel({studentId,subject,level,board,onClear,revision}:{studentId:string;subject:string;level:string;board:string;onClear:()=>void;revision:number}){
  const currentScope=`${studentId}:${subject}:${level}:${board}`;
  const scopeRef=useRef(currentScope);scopeRef.current=currentScope;
  const loadVersion=useRef(0);
  const [data,setData]=useState<Profile|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [exam,setExam]=useState('');const [topics,setTopics]=useState('');const [minutes,setMinutes]=useState(60);
  const [topic,setTopic]=useState('');const [earned,setEarned]=useState(0);const [possible,setPossible]=useState(10);const [busy,setBusy]=useState(false);
  const call=useCallback(async(action:string,extra:Record<string,unknown>={})=>{
    const response=await fetch(`/api/modules/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:studentId,subject,level,board,...extra})});
    const body=await response.json();if(!response.ok)throw new Error(body.detail||'Request failed.');return body;
  },[studentId,subject,level,board]);
  const load=useCallback(async()=>{if(!studentId)return;const version=++loadVersion.current;try{setError('');const body=await call('profile');if(scopeRef.current!==currentScope||version!==loadVersion.current)return;setData(body);if(body.plan?.daily_minutes)setMinutes(body.plan.daily_minutes);}catch(e){if(scopeRef.current===currentScope&&version===loadVersion.current)setError(e instanceof Error?e.message:'Could not load your learning record.');}},[studentId,call,currentScope]);
  useEffect(()=>{setData(null);setTopics('');setExam('');load();},[load]);
  useEffect(()=>setNotice(''),[subject,level,board]);
  useEffect(()=>{if(revision)load();},[revision,load]);
  async function plan(event:FormEvent){event.preventDefault();const expected=scopeRef.current;setBusy(true);setError('');try{const body=await call('planner',{exam_date:exam||data?.profile.exam_date,topics:topics.split('\n').map(t=>t.trim()).filter(Boolean),daily_minutes:minutes});if(scopeRef.current!==expected)return;setData(previous=>previous?{...previous,plan:body}:previous);setNotice('Study plan saved. New scores automatically update its remaining sessions.');}catch(e){if(scopeRef.current===expected)setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  async function score(event:FormEvent){event.preventDefault();const expected=scopeRef.current;setBusy(true);setError('');try{await call('scores',{topic,earned,possible});if(scopeRef.current!==expected)return;await load();setNotice('Self-reported score saved and your remaining plan recalculated.');}catch(e){if(scopeRef.current===expected)setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  async function clear(){setBusy(true);try{await call('memory/clear');setData(null);onClear();setNotice('Stored learning records deleted.');}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  return <section className="learning-panel" id="learning-plan"><h2>Your learning plan</h2><p>Save an exam date, prioritize weaker topics and keep the day before the exam free.</p>
    <form onSubmit={plan}><fieldset disabled={busy||!studentId}><div className="persona-fields"><label>Exam date<input required type="date" value={exam||data?.profile.exam_date||''} onChange={e=>setExam(e.target.value)}/></label><label>Minutes per day<input required type="number" min={30} max={480} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div><label>Topics, one per line<textarea rows={4} value={topics} maxLength={20000} onChange={e=>setTopics(e.target.value)} placeholder={data?.syllabus_topics.length?'Leave blank to use the teacher’s syllabus topics.':'Enter the topics you need to study.'}/></label><button className="primary-button">{busy?'Saving...':'Build my plan'}</button></fieldset></form>
    {data?.plan&&<div className="plan-result"><h3>{data.plan.exam_date?`Exam: ${data.plan.exam_date}`:'Saved plan'}</h3>{data.plan.free_day&&<p>Kept free: {data.plan.free_day}</p>}{data.plan.message&&<p>{data.plan.message}</p>}{data.plan.warning&&<p role="status">{data.plan.warning}</p>}<details open><summary>Study schedule ({data.plan.schedule?.length||0} days)</summary><div className="schedule-list">{data.plan.schedule?.map(day=><div key={day.date}><h4>{day.date}</h4>{day.sessions.map((session,i)=><p key={i}><strong>{session.topic}</strong> · {session.minutes} min<br/><small>{session.activity}</small></p>)}</div>)}</div></details></div>}
    <details className="learning-details"><summary>Record a practice score</summary><p>Self-assess using the mock answer guide or enter teacher-provided marks. These are not automatically graded scores.</p><form onSubmit={score}><fieldset disabled={busy||!studentId}><label>Topic<input value={topic} required maxLength={200} onChange={e=>setTopic(e.target.value)}/></label><div className="persona-fields"><label>Marks earned<input type="number" required min={0} max={possible} step="0.5" value={earned} onChange={e=>setEarned(Number(e.target.value))}/></label><label>Marks possible<input type="number" required min={1} max={200} step="0.5" value={possible} onChange={e=>setPossible(Number(e.target.value))}/></label></div><button className="primary-button">Save score</button></fieldset></form>{Object.entries(data?.profile.scores||{}).map(([name,value])=><p key={name}>{name}: <strong>{value}%</strong></p>)}</details>
    <details className="learning-details"><summary>Saved dialogue and privacy</summary><p>Your random guest identity is stored in this browser. Dialogue and learning records are encrypted on the server and expire after the configured retention period. Anyone using this browser profile can access this guest workspace.</p>{data?.history.map((turn,i)=><details key={i}><summary>{turn.role==='user'?'You':'StudyMate'}: {turn.message.slice(0,90)}</summary><p className="saved-message">{turn.message}</p></details>)}<button className="text-button" disabled={busy} onClick={clear}>Delete all my saved learning records</button></details>
    {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="persona-error">{error}</p>}
  </section>;
}
