"use client";
import {useEffect,useState,useRef} from 'react';
export default function VoiceTools({onTranscript,answer,language}:{onTranscript:(text:string,language:string)=>void;answer?:string;language:string}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [audio,setAudio]=useState('');const url=useRef('');const activeAnswer=useRef(answer);activeAnswer.current=answer;const alive=useRef(true);const controller=useRef<AbortController|null>(null);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();if(url.current)URL.revokeObjectURL(url.current);};},[]);
  useEffect(()=>{if(url.current)URL.revokeObjectURL(url.current);url.current='';setAudio('');setError('');},[answer]);
  async function transcribe(file:File){controller.current=new AbortController();setBusy(true);setError('');try{if(file.size>10*1024*1024)throw new Error('Use an audio file under 10 MB.');const response=await fetch('/api/modules/voice/transcribe',{method:'POST',body:file,signal:controller.current.signal});const data=await response.json();if(!response.ok)throw new Error(data.detail);if(alive.current)onTranscript(data.text,data.language);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  async function speak(){const requestedAnswer=answer;controller.current=new AbortController();setBusy(true);setError('');try{const response=await fetch('/api/modules/voice/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:answer?.slice(0,5000),language}),signal:controller.current.signal});if(!response.ok)throw new Error((await response.json()).detail);const blob=await response.blob();if(!alive.current||activeAnswer.current!==requestedAnswer)return;if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(blob);setAudio(url.current);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  return <details className="voice-tools"><summary>Voice input and output</summary><p>Transcribe the first two minutes of an audio file locally with Whisper. Review the text before sending.</p><label>Audio file (up to 10 MB)<input type="file" accept="audio/*" disabled={busy} onChange={e=>{if(e.target.files?.[0])transcribe(e.target.files[0]);e.target.value='';}}/></label>{answer&&<><p>Google text-to-speech sends the answer text to Google. It must be enabled by the server operator.</p><button className="text-button" disabled={busy} onClick={speak}>Create spoken answer with Google TTS</button></>}{busy&&<p role="status">Processing audio...</p>}{audio&&<audio controls src={audio}/>} {error&&<p role="alert" className="persona-error">{error}</p>}</details>;
}
