"use client";
import {useState,type FormEvent} from 'react';
type Analytics={queries:Record<string,number>;confusion:Record<string,number>;persona_usage:Record<string,number>;scores:Record<string,{count:number;mean:number;below_50:number}>;syllabus_coverage:Record<string,{topics:number;queried:number}>;retention_days:number};
export default function Teacher(){
  const [key,setKey]=useState('');const [data,setData]=useState<Analytics|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const [subject,setSubject]=useState('physics');const [level,setLevel]=useState('PUC2');const [board,setBoard]=useState('KA');const [topics,setTopics]=useState('');const [questions,setQuestions]=useState('');
  const [file,setFile]=useState<File|null>(null);const [kind,setKind]=useState('textbook');const [job,setJob]=useState('');
  async function call(path:string,body?:unknown){const form=body instanceof FormData;const response=await fetch(`/api/modules/teacher/${path}`,{method:body?'POST':'GET',headers:{'X-Teacher-Key':key,...(body&&!form?{'Content-Type':'application/json'}:{})},body:body?(form?body:JSON.stringify(body)):undefined});const result=await response.json();if(!response.ok)throw new Error(result.detail);return result;}
  async function run(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  return <main className="teacher-page"><a href="/" className="text-button">Back to study workspace</a><h1>Teacher tools</h1><p>Inspect aggregated learning activity and maintain the course corpus. Student accounts are not required.</p>
    <form onSubmit={e=>{e.preventDefault();run(async()=>setData(await call('analytics')));}}><label>Teacher access key<input type="password" autoComplete="off" value={key} onChange={e=>{setKey(e.target.value);setData(null);}} required placeholder="Configured by the server operator"/></label><button disabled={busy} className="primary-button">Load analytics</button></form>
    {error&&<p role="alert" className="persona-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {data&&<section><h2>Learning activity</h2><p>Retained for {data.retention_days} days. Scores are self-reported; repeated clarification is a proxy for confusion.</p><div className="teacher-tables"><div><h3>Topics and confusion</h3><table><thead><tr><th>Course / topic</th><th>Queries</th><th>Clarifications</th></tr></thead><tbody>{Object.entries(data.queries).map(([topic,count])=><tr key={topic}><td>{topic}</td><td>{count}</td><td style={{background:data.confusion[topic]?'#e8f0e7':undefined}}>{data.confusion[topic]||0}</td></tr>)}</tbody></table>{!Object.keys(data.queries).length&&<p>No learning activity yet.</p>}</div><div><h3>Practice scores</h3><table><thead><tr><th>Course / topic</th><th>Mean</th><th>Below 50%</th></tr></thead><tbody>{Object.entries(data.scores).map(([topic,s])=><tr key={topic}><td>{topic}</td><td>{s.mean}% ({s.count})</td><td>{s.below_50}</td></tr>)}</tbody></table></div></div><h3>Syllabus coverage</h3>{Object.entries(data.syllabus_coverage).map(([course,s])=><p key={course}>{course}: {s.queried} of {s.topics} topics queried</p>)}<h3>Persona usage</h3>{Object.entries(data.persona_usage).map(([id,count])=><p key={id}>{id}: {count} requests</p>)}</section>}
    <section><h2>Course material</h2><div className="course-fields"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{['physics','chemistry','mathematics','biology'].map(s=><option key={s}>{s}</option>)}</select></label><label>Year<select value={level} onChange={e=>setLevel(e.target.value)}><option>PUC1</option><option>PUC2</option></select></label><label>Board<select value={board} onChange={e=>setBoard(e.target.value)}><option>KA</option><option>CBSE</option></select></label></div>
      <form onSubmit={e=>{e.preventDefault();run(async()=>{await call('syllabus',{subject,level,board,topics:topics.split('\n').map(x=>x.trim()).filter(Boolean)});setNotice('Syllabus topics saved for planning and coverage.');});}}><label>Syllabus topics, one per line<textarea value={topics} required rows={6} onChange={e=>setTopics(e.target.value)}/></label><button disabled={busy||!key} className="primary-button">Save syllabus topics</button></form>
      <form onSubmit={e=>{e.preventDefault();run(async()=>{if(!file)throw new Error('Choose a PDF.');const form=new FormData();form.set('file',file);form.set('subject',subject);form.set('level',level);form.set('board',board);form.set('kind',kind);const result=await call('upload',form);setJob(result.job_id);setNotice('PDF uploaded. Indexing started; check the job below.');});}}><label>Source type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="textbook">Textbook / lecture notes</option><option value="syllabus">Syllabus PDF</option></select></label><label>PDF (up to 20 MB)<input type="file" accept="application/pdf" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={busy||!key} className="primary-button">Upload and index PDF</button></form>
      {job&&<button disabled={busy} className="text-button" onClick={()=>run(async()=>{const result=await call(`uploads/${job}`);setNotice(result.status==='ready'?'Index ready. The new material is available to students.':result.status==='failed'?result.error:'Still indexing...');})}>Check latest upload</button>}
      <details><summary>Import reviewed previous-year questions</summary><p>Paste a JSON array with subject, level, board, year, source, topic, text, marks and optional page. Reviewed records replace automatic extraction for their course.</p><pre>{JSON.stringify([{subject,level,board,year:2025,source:'Exam 2025',topic:'Waves',text:'Explain the principle of superposition.',marks:3,verified:true}],null,2)}</pre><form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await call('questions',JSON.parse(questions));setNotice(`${result.records} reviewed questions available.`);});}}><label>Reviewed questions JSON<textarea rows={8} value={questions} required onChange={e=>setQuestions(e.target.value)}/></label><button disabled={busy||!key} className="primary-button">Import reviewed questions</button></form></details>
    </section>
  </main>;
}
