import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('../tmp/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3000');
await page.getByText('Course index is empty',{exact:true}).waitFor();
await page.screenshot({path:'../tmp/screenshots/desktop.png',fullPage:true});
await page.getByLabel('What would you like to understand?').fill('Explain waves.');
await page.getByRole('button',{name:'Ask StudyMate',exact:true}).click();
await page.getByText(/I could not find supporting passages/).waitFor();
const calls=[];
await page.route('**/api/study/*',async route=>{
  if(route.request().method()!=='POST') return route.continue();
  calls.push({tool:route.request().url().split('/').pop(),body:route.request().postDataJSON()});
  await route.fulfill({json:{answer:'## Test fixture\n\nA grounded explanation [1].\n\nRetrieved sources\n[1] Physics.pdf | page 3'}});
});
for(const [nav,action,tool] of [['Ask a question','Ask StudyMate','ask'],['Guided learning','Start guided learning','socratic'],['Revision notes','Create revision notes','summary'],['Past paper review','Review past papers','pyq'],['Practice paper','Generate practice paper','mock-paper']]){
  await page.getByRole('button',{name:nav,exact:true}).click();
  if(tool==='summary') await page.getByLabel('Chapter or topic',{exact:true}).fill('Waves');
  await page.getByRole('button',{name:action,exact:true}).click();
  await page.getByRole('heading',{name:'Test fixture',exact:true}).waitFor();
  assert.equal(calls.at(-1).tool,tool);
  assert.equal(calls.at(-1).body.subject,'physics');
  assert.equal(calls.at(-1).body.level,'PUC2');
}
assert.equal(calls[2].body.summary_type,'bullet_points');
assert.equal(calls[4].body.total_marks,70);
await page.getByRole('button',{name:'Copy answer',exact:true}).click();
await page.getByRole('button',{name:'Copied',exact:true}).waitFor();
const download=page.waitForEvent('download');
await page.getByRole('button',{name:'Download notes',exact:true}).click();
assert.equal((await download).suggestedFilename(),'studymate-physics.txt');
await page.unroute('**/api/study/*');
await page.route('**/api/study/ask',route=>route.fulfill({status:503,json:{detail:'Start Ollama and try again.'}}));
await page.getByRole('button',{name:'Ask a question',exact:true}).click();
await page.getByRole('button',{name:'Ask StudyMate',exact:true}).click();
await page.getByRole('alert').getByText('Start Ollama and try again.').waitFor();
await page.getByRole('button',{name:'Clear session results'}).click();
await page.getByRole('button',{name:'Ask a question',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'../tmp/screenshots/mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile page must not overflow');
assert.equal(await page.getByRole('button',{name:/login|sign up/i}).count(),0);
assert.deepEqual(errors,[]);
console.log('PASS: live no-evidence response, five tool payloads, Markdown, copy, download, error recovery, mobile overflow, no authentication, no browser errors.');
await browser.close();
