import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3000');
await page.getByText('No educators for physics yet.',{exact:false}).waitFor();
await page.getByText('Add a YouTube lecture',{exact:true}).click();
await page.getByLabel('Educator name',{exact:true}).fill('Fixture lecturer');
await page.getByLabel('YouTube video URL',{exact:true}).fill('https://example.com/video');
await page.getByRole('button',{name:'Import lecture',exact:true}).click();
await page.getByRole('alert').getByText(/single YouTube video link/).waitFor();
const eid='1234567890abcdef12345678';let registered=false;let submitted;
const educator={id:eid,name:'Fixture lecturer',subject:'physics',ready:true,passage_count:8,descriptor:{sentence_length:'Short explanations',analogy_use:'Everyday analogies',transitions:'Step by step',vocabulary:'Accessible',teaching_approach:'Guided questions'},videos:[{id:'fixture',title:'Fixture lecture',url:'https://www.youtube.com/watch?v=abcdefghijk',status:'ready',error:null,passage_count:8,origin:'pasted'}]};
await page.route('**/api/personas',async route=>{
  if(route.request().method()==='POST'){submitted=route.request().postDataJSON();registered=true;return route.fulfill({status:202,json:{educator_id:eid,queued:true}});}
  return route.fulfill({json:{educators:registered?[educator]:[]}});
});
await page.getByLabel('YouTube video URL',{exact:true}).fill('https://youtu.be/abcdefghijk');
await page.getByLabel('Paste a transcript instead of fetching captions').check();
await page.getByLabel('Lecture transcript',{exact:true}).fill('A user-supplied transcript fixture. '.repeat(50));
await page.getByRole('button',{name:'Import lecture',exact:true}).click();
await page.getByText(/Import started/).waitFor();
assert.equal(submitted.subject,'physics');assert.ok(submitted.transcript.length>100);
await page.getByLabel('Teaching style').selectOption(eid);
await page.getByText('Add a YouTube lecture',{exact:true}).click();
await page.locator('.educator-detail summary').click();
await page.getByText('Short explanations',{exact:true}).waitFor();
await page.screenshot({path:'../tmp/screenshots/persona-desktop.png',fullPage:true});
let ask;
await page.route('**/api/study/ask',async route=>{ask=route.request().postDataJSON();return route.fulfill({json:{answer:'A test explanation from course material [1].',persona:{applied:true,name:'Fixture lecturer',reason:'Teaching style applied; facts come from course sources.',sources:[{title:'Fixture lecture',url:'https://youtube.com/watch?v=abcdefghijk&t=10',origin:'pasted'}]}}});});
await page.getByLabel('What would you like to understand?').fill('Explain waves');
await page.getByRole('button',{name:'Ask StudyMate',exact:true}).click();
await page.getByText(/Fixture lecturer: Teaching style applied/).waitFor();assert.equal(ask.persona_id,eid);
await page.getByText('Teaching-style references (not factual sources)').click();
await page.getByRole('link',{name:'Fixture lecture'}).last().waitFor();
await page.getByLabel('Subject').selectOption('biology');
assert.equal(await page.getByLabel('Teaching style').inputValue(),'');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'../tmp/screenshots/persona-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);
console.log('PASS: live invalid URL rejection, registration UI/payload, transcript fallback, educator selection/profile, persona request and source attribution, subject reset, responsive layout. Successful model data is mocked.');
await browser.close();
